package canopen

import (
	utilsPkg "canopen/utils"
	logPkg "canopen/utils/gologtofile"
	"context"
	"encoding/binary"
	"fmt"
	"os"
	"time"

	"github.com/angelodlfrtr/go-can"
	"github.com/angelodlfrtr/go-can/transports"
	"golang.org/x/sync/semaphore"
)

// =====================================
// CANopen: Master/Slave protocols Model
// =====================================
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Here are some common CANopen protocols that follow the master/slave communication model:
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//
// 1- NMT (Network Management):    Network Management is a crucial part of CANopen.
//                                 It defines the states of the devices on the network and their transitions.
//                                 The master node manages the NMT state changes of the slave nodes.
//
// 2. SDO (Service Data Object):   SDO is used for parameterization and configuration of devices.
//                                 The master initiates SDO communication to read or write parameters on slave devices.
//
// 3; PDO (Process Data Object):   PDOs are used for cyclic real-time data exchange between devices.
//                                 Master nodes configure PDO communication, and slaves transmit process data in
//                                 response to PDO requests from the master.
//
// 4. Sync (Synchronous):          The SYNC protocol is used to synchronize the timing of PDO transmissions in the
//                                 network.
//                                 The master sends SYNC messages at regular intervals, allowing synchronized data
//                                 exchange.
//
// 5. Emergency Messages:          Slaves can send emergency messages to the master if a critical fault occurs.
//                                 The master can take appropriate action based on these messages.
//
// 6. Heartbeat:                   Slaves often send heartbeat messages to the master to indicate their operational
//                                 status.
//                                 The master can monitor these messages and take action if a slave becomes unresponsive.
//
// 7; LSS (Layer Setting Services): LSS allows for configuration of CANopen devices, including assigning node IDs and setting
//                                  communication parameters. The master can initiate LSS configuration.
//                                  It's important to note that while these protocols typically follow a master/slave
//                                  communication model, CANopen is quite flexible, and different devices might
//                                  implement additional communication patterns or adapt the basic protocols in various
//                                  ways to suit specific application requirements.
// ======================================
// CANopen: Client/Server protocols Model
// ======================================
// 1. SDO (Service Data Object):     SDOs are used for parameterization and configuration of devices.
//                                   In the context of SDO, a "Client" initiates the request for data (Read) or
//                                   sends data for storage (Write), and a "Server" responds accordingly.
//                                   The master (acting as the Client) sends requests to specific objects on a
//                                   slave device (acting as the Server) to read or write data.
// ==========================================
// CANopen: Producer/Consumer protocols Model
// ==========================================
//                                   This model is used for real-time data exchange between devices in a distributed
//                                   control system.
// In the Producer/Consumer model:
//
// Producer:                         A device (often a sensor or a data source) that generates data at a regular
//                                   interval or in response to an event.
//                                   This device "produces" data that needs to be transmitted to other devices on
//                                   the network.
//
// Consumer:                         A device (often a controller or an actuator) that needs to receive and process
//                                   the data generated by the producer.
//                                   This device "consumes" the data to make decisions or take actions.

var CanBusTransportSocket *transports.SocketCan = nil
var CanBusHandler *can.Bus = nil
var CanBusPortName string = "can"
var CanBusPortAddress uint8 = 0
var CanBusIsConnected bool = false
var CanBusServicesRunning bool = false

// GoLang semaphores for 10 concurreny tasks
var CanBusSem = semaphore.NewWeighted(int64(10))
var CanBusCtx = context.Background()

// CanBusConnect make a connection with a Device
func CanBusConnect(canBusPortName string, canBusPortAddress uint8) bool {
	var CanBusFUllPortName string = canBusPortName
	if len(canBusPortName) > 0 {
		CanBusFUllPortName = fmt.Sprintf("%s%d", canBusPortName, int(canBusPortAddress))
	}

	// WINDOWS: has no can.bus adapter
	if os.PathSeparator == '\\' && os.PathListSeparator == ';' {
		CanBusIsConnected = false
		logPkg.CtsLog.Error("FAIL:CanBusConnect: CanBusFUllPortName[%s] Windows has no can.bus adapter\n", CanBusFUllPortName)
		return false
	}

	// Configuring CanOpen transport
	CanBusTransportSocket = &transports.SocketCan{
		Interface: CanBusFUllPortName, // can0 or vcan0
	}
	// Open CanOpen bus
	CanBusHandler = can.NewBus(CanBusTransportSocket)
	err := CanBusHandler.Open()
	if err != nil {
		CanBusHandler = nil
		CanBusTransportSocket = nil
		if !CanBusIsConnected {
			CanBusIsConnected = false
			logPkg.CtsLog.Error("FAIL:CanBusConnect: CanBusFUllPortName[%s] err[%v]\n", CanBusFUllPortName, err)
		}
		return false
	}
	err = CanBusHandler.Transport.Open()
	if err != nil {
		CanBusHandler.Close()
		CanBusHandler = nil
		CanBusTransportSocket = nil
		CanBusIsConnected = false
		logPkg.CtsLog.Error("FAIL:CanBusConnect: CanBusFUllPortName[%s] err[%v]\n", CanBusFUllPortName, err)
		return false
	}
	logPkg.CtsLog.Info("PASS - " + CanBusFUllPortName + " is Working in CanOpen.")
	CanBusIsConnected = true
	return true
}

func SendCanFrame(bus *can.Bus, arbitrationId uint32, data []byte) error {

	if CanBusHandler == nil {
		CanBusIsConnected = CanBusConnect(CanBusPortName, CanBusPortAddress)
	}
	if !CanBusIsConnected {
		logPkg.CtsLog.Error("FAIL:CanUpenPortName[%s] Disconnected", CanBusPortName)
		return fmt.Errorf("CanUpenPortName[%s%d]Disconnected", CanBusPortName, int(CanBusPortAddress))
	}
	// ==========================================
	// Send: can.frame >> CanOpen: Remote Rqu/Rsp
	// ==========================================
	///pdoMessage := Message{
	///	CobID:     0x201, canFrame.ArbitrationID                                                    // PDO identifier
	///	RTR:       0,
	///	Length:    8,     canFrame.DLC                                                      // Length of the data
	///	Data:      [8]byte{0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08}, // Data payload
	///	Timestamp: time.Now(),
	///}
	canFrame := &can.Frame{
		ArbitrationID: arbitrationId, //  ID + RTR
		DLC:           8,             // Data Length
		Data:          [8]byte(data),
	}
	ParseCanBusFrame(canFrame)

	// TODO_WINDOWS: In case of Windows Simulate that is connected
	//if os.PathSeparator == '\\' && os.PathListSeparator == ';' {
	//	return nil
	//}

	// Sending CanOpen Frame
	CanBusSem.Acquire(CanBusCtx, 1)
	err := bus.Write(canFrame)
	if err != nil {
		logPkg.CtsLog.Error("FAIL:CanOpenSendData:  err[%v]", err)
		CanBusSem.Release(1)
		return err
	}
	logPkg.CtsLog.Info("CanOpenSendData:bus.Write(frm) Sent >> arbitrationId[%d] data[%v]\n", arbitrationId, data)
	CanBusSem.Release(1)
	return nil
}

func RecvCanFrame(bus *can.Bus, arbitrationId uint32) ([8]byte, error) {
	//efetua a leitura da memoria
	var returnData [8]byte
	EmtyData := []byte{0, 0, 0, 0, 0, 0, 0, 0}

	if CanBusHandler == nil {
		CanBusIsConnected = CanBusConnect(CanBusPortName, CanBusPortAddress)
	}
	if !CanBusIsConnected {
		logPkg.CtsLog.Error("FAIL:CanUpenPortName[%s%d] Disconnected", CanBusPortName, CanBusPortAddress)
		return returnData, fmt.Errorf("CanUpenPortName[%s%d]Disconnecteds", CanBusPortName, CanBusPortAddress)
	}

	copy(returnData[:], EmtyData)

	// TODO_WINDOWS: In case of Windows Simulate that is connected
	//if os.PathSeparator == '\\' && os.PathListSeparator == ';' {
	//	return returnData, nil
	//}

	CanBusSem.Acquire(CanBusCtx, 1)
	timer := time.NewTimer(30 * time.Second)
	select {
	case canFrame := <-bus.ReadChan():
		// ==========================================
		// Recv: can.frame << CanOpen: Remote Rqu/Rsp
		// ==========================================
		///pdoMessage := Message{
		///	CobID:     0x201, canFrame.ArbitrationID                                                    // PDO identifier
		///	RTR:       0,
		///	Length:    8,     canFrame.DLC                                                      // Length of the data
		///	Data:      [8]byte{0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08}, // Data payload
		///	Timestamp: time.Now(),
		///}
		aid := canFrame.ArbitrationID  /// CobID(CAN-ID+NodeID) + RTR
		dlc := canFrame.DLC            /// Data Length
		rcvddata := canFrame.GetData() /// Data
		copy(returnData[:], rcvddata)
		ParseCanBusFrame(canFrame)
		logPkg.CtsLog.Info("CanOpenRecvData Rcvd << aid[%X] dlc[%X] rcvddata[%X] returnData[%X]\n", aid, dlc, rcvddata, returnData)
		CanBusSem.Release(1)
		return returnData, nil
	case <-timer.C:
		logPkg.CtsLog.Error("CanOpenRecvData:FAIL bus.ReadChan() timer.C[%v] Timeout\n", timer.C)
		CanBusSem.Release(1)
		return returnData, fmt.Errorf("CanOpenRecvData:FAIL bus.ReadChan() Timeout timer.C[%v]", timer.C)
	}
}

// GoRotine for Recv Can Frames
func RunCanBusRecvService(dev utilsPkg.DevSettings) error {
	var arbitrationId uint32 = 0x600
	var iOldErrorCode = 0
	var iCurErrorCode = 0
	logPkg.CtsLog.Debug("RunCanBusRecvService: Started\n")
	for {
		readHour := time.Now()
		readTime := readHour.Format("2006-01-02 15:04:05")
		if utilsPkg.AnyDevicelsRunning {
			data, err := RecvCanFrame(CanBusHandler, arbitrationId)
			if err != nil {
				iCurErrorCode = 21
				if iCurErrorCode != iOldErrorCode {
					iOldErrorCode = iCurErrorCode
					logPkg.CtsLog.Error("RunCanBusRecvService: fail err[%s]\n", err)
					msgLog := utilsPkg.MqttLogMsg{
						Address:  dev.Address,
						Port:     dev.Port,
						Name:     dev.Name,
						Protocol: dev.Protocol,
						Id:       dev.Id,
						Time:     readTime,
						Message:  "Fail to Read CAN frame",
						Code:     "CANOPEN_" + fmt.Sprintf("%03d", iCurErrorCode),
						Source:   fmt.Sprint("RunCanBusRecvService  CANopen dev[", dev.Address, "]"),
					}
					_ = MQTTSendLogMessage(msgLog, "error")
				}
				time.Sleep(time.Duration(5000) * time.Millisecond)
			} else {
				logPkg.CtsLog.Info("RunCanBusRecvService: << Rcvd CAN data[%X]\n", data)
			}
		}
		if !CanBusServicesRunning {
			break // Exiting Closed Loop
		}
		time.Sleep(time.Duration(100) * time.Millisecond)
		// TODO__WINDOWS: In case of Windows Simulate that is connected
		if os.PathSeparator == '\\' && os.PathListSeparator == ';' {
			time.Sleep(time.Duration(5000) * time.Millisecond)
		}

	} // End Closed Loop
	return nil
}

// GoRotine for Send Can Frames
func RunCanBusSendService(dev utilsPkg.DevSettings) error {
	var arbitrationId uint32 = 0x600
	var iOldErrorCode = 0
	var iCurErrorCode = 0
	data := []byte{0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08}
	logPkg.CtsLog.Debug("RunCanBusSendService: Started\n")
	for {
		readHour := time.Now()
		readTime := readHour.Format("2006-01-02 15:04:05")
		if utilsPkg.AnyDevicelsRunning {
			err := SendCanFrame(CanBusHandler, arbitrationId, data)
			if err != nil {
				logPkg.CtsLog.Error("RunCanBusSendService: fail err[%s]\n", err)
				iCurErrorCode = 22
				if iCurErrorCode != iOldErrorCode {
					iOldErrorCode = iCurErrorCode
					logPkg.CtsLog.Error("RunCanBusSendService: fail err[%s]\n", err)
					msgLog := utilsPkg.MqttLogMsg{
						Address:  dev.Address,
						Port:     dev.Port,
						Name:     dev.Name,
						Protocol: dev.Protocol,
						Id:       dev.Id,
						Time:     readTime,
						Message:  "Fail to Read CAN frame",
						Code:     "CANOPEN_" + fmt.Sprintf("%03d", iCurErrorCode),
						Source:   fmt.Sprint("RunCanBusSendService  CANopen dev[", dev.Address, "]"),
					}
					_ = MQTTSendLogMessage(msgLog, "error")
				}
				time.Sleep(time.Duration(5000) * time.Millisecond)
			} else {
				logPkg.CtsLog.Info("RunCanBusSendService: >> Send CAN data[%X]\n", data)
			}
		}
		if !CanBusServicesRunning {
			break // Exiting Closed Loop
		}
		// TODO_WINDOWS: In case of Windows Simulate that is connected
		if os.PathSeparator == '\\' && os.PathListSeparator == ';' {
			time.Sleep(time.Duration(5000) * time.Millisecond)
		}
		time.Sleep(time.Duration(100) * time.Millisecond)
	} // End Closed Loop
	return nil
}

func ParseCanBusFrame(inCanFrame *can.Frame) error {
	// Check if inCanFrame is not null and is CanOpen
	if inCanFrame == nil {
		return fmt.Errorf("FAIL: incanframe= null")
	}
	rawCanBusFrame, err := ConvertCanBusFrameToBytes(inCanFrame)
	if err != nil {
		logPkg.CtsLog.Error("Error: err[%s]", err)
		return err
	}
	isCanOpen, err := ParseRawCanBusFrame(rawCanBusFrame)
	if err != nil {
		logPkg.CtsLog.Error("Error:isCanOpen[%v]  err[%s]", isCanOpen, err)
		return err
	}
	return nil
}

// This Function decodes detailed of CANopen byte array message
// if all required data are present return nil else return error message explaining the reason of failure
func ParseRawCanBusFrame(rawCanBusFrame []byte) (bool, error) {
	// Converte Raw CAN Frame to CAN frame
	if rawCanBusFrame == nil {
		logPkg.CtsLog.Error("ParseRawCanBusFrame:ER can frame=nil CANRawFrame[%X]", len(rawCanBusFrame))
		return false, fmt.Errorf("ParseRawCanBusFrame:ER can frame=nil CANRawFrame[%X]", len(rawCanBusFrame))
	} else if len(rawCanBusFrame) < 4 {
		logPkg.CtsLog.Error("ParseRawCanBusFrame:ER can frame Too Short Exp len(CANRawFrame) >=4 rcv len(CANRawFrame)[%d]", len(rawCanBusFrame))
		return false, fmt.Errorf("ParseRawCanBusFrame:ER can frame Too Short Exp len(CANRawFrame) >=4 rcv len(CANRawFrame)[%d]", len(rawCanBusFrame))
	} else if len(rawCanBusFrame) > 13 {
		logPkg.CtsLog.Error("ParseRawCanBusFrame:ER can frame Too long Exp len(data) <=13 rcv len(data)[%d]", len(rawCanBusFrame))
		return false, fmt.Errorf("ParseRawCanBusFrame:ER can frame too long Exp len(data) <=13 rcv len(data)[%d]", len(rawCanBusFrame))
	}

	id := binary.BigEndian.Uint32(rawCanBusFrame[:4]) // Bytes 0-3
	dlc := rawCanBusFrame[4] & 0x0F                   // Byte 4 b0-3
	ext := (rawCanBusFrame[4] & 0x80) != 0            // Byte 4 b7
	rtr := (rawCanBusFrame[4] & 0x40) != 0            // Byte 4 b6
	if len(rawCanBusFrame) < int(dlc)+5 {
		logPkg.CtsLog.Error("ParseRawCanBusFrame:ER invalid can frame len(CANRawFrame)[%d] < int(dlc)+4[%d]", len(rawCanBusFrame), int(dlc)+5)
		return false, fmt.Errorf("ParseRawCanBusFrame:ER invalid can frame len(CANRawFrame)[%d] < int(dlc)+4[%d]", len(rawCanBusFrame), int(dlc)+5)
	} else if len(rawCanBusFrame) > int(dlc)+5 {
		logPkg.CtsLog.Error("ParseRawCanBusFrame:ER invalid can frame len(data)[%d] > int(dlc)+4[%d]", len(rawCanBusFrame), int(dlc)+5)
		return false, fmt.Errorf("ParseRawCanBusFrame:ER invalid can frame len(data)[%d] > int(dlc)+4[%d]", len(rawCanBusFrame), int(dlc)+5)
	}
	// It is a CanBus frame, now we check if it is a CANopen frame present on CanBus
	canFrame := &CANOPEN_Frame{ // canopenControl.go
		ID:   id,                        // 32 bits bytes 0-3
		DLC:  dlc,                       //  4 Bits byte  4 bits (0-3) byte 4 b7 ext byte 4 b6 RNR byte 4 bits 4-5 N/A
		Data: rawCanBusFrame[5 : 5+dlc], //  8 Bits Bytes 5-12
	}
	if canFrame.DLC != uint8(len(canFrame.Data)) {
		logPkg.CtsLog.Error("ParseRawCanBusFrame:ER invalid can frame: canFrame DLC[%d] != len(canFrame Data)[%d]", canFrame.DLC, len(canFrame.Data))
		return false, fmt.Errorf("ParseRawCanBusFrame:ER invalid can frame: canFrame DLC[%d] != len(canFrame Data)[%d]", canFrame.DLC, len(canFrame.Data))
	}
	if !ext {
		// CIA301a: ID = 11 bits
		err := ParseCANopen_CIA301aFrame(canFrame) // canopenControl.go
		if err != nil {
			///FAIL to Parse a CANopen Frame
			logPkg.CtsLog.Warn("ParseRawCanBusFrame:WR Is a CAN frame but not CANopen Frame msg[%s]", err)
			return false, nil
		}
	} else {
		// CIA301b: ID = 29 bits
		err := ParseCANopen_CIA301bFrame(canFrame) // canopenControl.go
		if err != nil {
			logPkg.CtsLog.Warn("ParseRawCanBusFrame:WR Is a CAN frame but not CANopen Frame msg[%s]", err)
			return false, nil
		}
	}
	// Valid CANopen Frame was Read on CanBus interface
	logPkg.CtsLog.Debug("ParseRawCanBusFrame:OK << ParseRawCanBusFrame[%X] id[%X] dlc[%d] ext[%v] rtr[%v] data[%X]Valid CANopen Frame was Read on CanBus interface", rawCanBusFrame, id, dlc, ext, rtr, canFrame.Data)
	return true, nil
}

func ConvertCanBusFrameToBytes(inCanFrame *can.Frame) ([]byte, error) {
	// Determine the length of the CAN frame
	frameLength := len(inCanFrame.Data) + 5 // CanFame id(4) DLC(1)

	// CANopenTcpServer_Create a byte slice with the appropriate length
	outRawCanFrame := make([]byte, frameLength)
	outRawCanFrame[0] = byte(inCanFrame.ArbitrationID >> 24)
	outRawCanFrame[1] = byte(inCanFrame.ArbitrationID >> 16)
	outRawCanFrame[2] = byte(inCanFrame.ArbitrationID >> 8)
	outRawCanFrame[3] = byte(inCanFrame.ArbitrationID)
	outRawCanFrame[4] = byte(inCanFrame.DLC)
	for i := 0; i < len(inCanFrame.Data); i++ {
		outRawCanFrame[i+5] = inCanFrame.Data[i]
	}
	return outRawCanFrame, nil
}

func ConvertRawBytesToCanBusFrame(inRawCanFrame []byte) (*can.Frame, error) {
	if inRawCanFrame == nil {
		logPkg.CtsLog.Error("ConvertRawBytesToCanBusFrame:ER can frame=nil CANRawFrame[%X]", len(inRawCanFrame))
		return nil, fmt.Errorf("ConvertRawBytesToCanBusFrame:ER can frame=nil CANRawFrame[%X]", len(inRawCanFrame))
	} else if len(inRawCanFrame) < 4 {
		logPkg.CtsLog.Error("ConvertRawBytesToCanBusFrame:ER can frame Too Short Exp len(CANRawFrame) >=4 rcv len(CANRawFrame)[%d]", len(inRawCanFrame))
		return nil, fmt.Errorf("ConvertRawBytesToCanBusFrame:ER can frame Too Short Exp len(CANRawFrame) >=4 rcv len(CANRawFrame)[%d]", len(inRawCanFrame))
	} else if len(inRawCanFrame) > 13 {
		logPkg.CtsLog.Error("ConvertRawBytesToCanBusFrame:ER can frame Too long Exp len(data) <=13 rcv len(data)[%d]", len(inRawCanFrame))
		return nil, fmt.Errorf("ConvertRawBytesToCanBusFrame:ER can frame too long Exp len(data) <=13 rcv len(data)[%d]", len(inRawCanFrame))
	}
	//CanFrame ID = 32 bits
	id := uint32(inRawCanFrame[0]) << 24
	id += uint32(inRawCanFrame[1]) << 16
	id += uint32(inRawCanFrame[2]) << 8
	id += uint32(inRawCanFrame[3])
	//CanFrame DLC = 4 byts
	dlc := inRawCanFrame[4] & 0x0F
	if int(dlc) != len(inRawCanFrame)-4 {
		logPkg.CtsLog.Error("ConvertRawBytesToCanBusFrame:ER can frame Too long Exp len(data) <=13 rcv len(data)[%d]", len(inRawCanFrame))
		return nil, fmt.Errorf("ConvertRawBytesToCanBusFrame:ER can frame too long Exp len(data) <=13 rcv len(data)[%d]", len(inRawCanFrame))
	}
	i := 0
	// Looks line a CanBus frame
	//CanFrame Data = 0-8 bytes
	var data [8]byte
	for {
		if i > int(dlc) {
			break
		}
		data[i] = inRawCanFrame[i+4]
	}
	canBusFrame := &can.Frame{
		ArbitrationID: id,  //  ID + RTR
		DLC:           dlc, // Data Length
		Data:          data,
	}
	return canBusFrame, nil
}
